version: '3'
services:
  redis:
      image: "redis"
      ports: 
      - "6379:6379"
  mvcapp2:
    image: "xmvcapp"
    environment:
     - "ASPNETCORE_ENVIRONMENT=Development"
    depends_on: 
     - "redis"
    ports:
     - "80:80"
  # mongo:
  #   image: "mongo"
  #   ports: 
  #    - "27017:27017"